### PR TITLE
fix(selenium): download jar files and not zip files

### LINKED ISSUE #370: downloading selenium incorrectly
Hi. I’m running into a problem where webdriver-manager is downloading a zip and renaming it .jar and then I get a corrupt jarfile.

```curl -o/Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-4.0.0-alpha-1.zip.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-1.zip```

This is of course not a proper jar file and later I get

```[webdriver] Error: Invalid or corrupt jarfile /home/circleci/project/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-4.0.0-alpha-1.zip.jar```

running it from bash this is the output.

```
Admins-MacBook-Pro:bin smonasco$ ./webdriver-manager update --standalone
webdriver-manager: using global installed version 12.1.1
[13:34:08] I/update - chromedriver: file exists /Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.46.zip
[13:34:08] I/update - chromedriver: unzipping chromedriver_2.46.zip
[13:34:08] I/update - chromedriver: setting permissions to 0755 for /Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.46
[13:34:08] I/update - chromedriver: chromedriver_2.46 up to date
[13:34:08] I/downloader - curl -o/Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-4.0.0-alpha-1.zip.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-1.zip
[13:34:09] I/update - geckodriver: file exists /Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz
[13:34:09] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[13:34:09] I/update - geckodriver: setting permissions to 0755 for /Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
[13:34:09] I/update - geckodriver: geckodriver-v0.24.0 up to date
Admins-MacBook-Pro:bin smonasco$ pwd
/Users/smonasco/spartan/node_modules/protractor/node_modules/webdriver-manager/bin
Admins-MacBook-Pro:bin smonasco$ 
```

### PR DESCRIPTION
**Pull request by cnishina**
This fix is here because selenium now has .zip files in the .xml. This
worked previously since there were no .zip files and it would find the
first version that matched the latest jar file.

Fix for legacy branch to update.

Closes #370

### CODE REVIEW

**Comment by cnishina** [comment]
We currently block "beta" releases but this appears to be an alpha release. This naming scheme does match up with the node module client we are using. I'm not sure if we should be using alpha versions.

**Comment by cnishina** [comment]
We will need to have a 12.1.2 release. This can't be beta versioned.

File: lib/binaries/standalone_xml.ts [hunk 1]
```diff
@@ -40,6 +40,9 @@ export class StandaloneXml extends XmlConfigSource {
       let latest = '';
       let latestVersion = '';
       for (let item of list) {
+        if (!item.endsWith('.jar')) {
```
Comment (heathkit) [inline lib/binaries/standalone_xml.ts]: instead of this, maybe filter the list?

let jarList = list.filter((i) => i.endsWith('.jar');

Comment (cnishina) [reply lib/binaries/standalone_xml.ts]: Sure?  It doesn't matter to me since this is from the legacy branch. Is this for efficiency or readability?

**Comment by cnishina** [comment]
Also we should discuss if alpha jar files is a thing we should be downloading.

File: lib/binaries/standalone_xml.ts (hunk 1 above)
Comment (cnishina) [reply lib/binaries/standalone_xml.ts]: Done.

**Comment by anmarcek** [comment]
My preference is to avoid alpha files as well - unless explicitly requested by the update command's "versions" parameter.

**Comment by cnishina** [comment]
Done. Removing alpha versions. It makes sense since we are not downloading beta versions.

**Comment by cnishina** [comment]
With the fix (version was updated here but not part of this PR):

```
node bin/webdriver-manager update --gecko false --chrome false
webdriver-manager: using project version 12.1.2
[10:26:18] I/config_source - curl -o/Users/cnishina/src/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[10:26:18] I/downloader - curl -o/Users/cnishina/src/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
```

The latest we will download is 3.141.59 and not the 4 alpha version.
