### PR TITLE
fix(ignoressl): pass ignore ssl down to the binary and config source

### LINKED ISSUE #207: webdriver-manager update --ignore_ssl no longer works on 12.0.1
**Actual Behavior**
Run the following against webdriver-manager version 12.0.1:

> webdriver-manager update --ignore_ssl

It returns

    events.js:160
        throw er; // Unhandled 'error' event
        ^

    Error: self signed certificate in certificate chain
        at Error (native)
        at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
        at emitNone (events.js:86:13)
        at TLSSocket.emit (events.js:185:7)
        at TLSSocket._finishInit (_tls_wrap.js:584:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

**Expected Behavior**
Based on version 10.2.5, I'm expecting something similar to:

    webdriver-manager: using local installed version 10.2.5
    [13:51:46] I/downloader - ignoring SSL certificate
    [13:51:46] I/downloader - ignoring SSL certificate
    [13:51:46] I/downloader - ignoring SSL certificate

**Why is this required?**
I'm working on an application for my company which is using some security measure that replaces a site's certificate with its own self-signed certificate. As a result, I have two options. Add my certificate to a store and somehow get webdriver-manager to use it. This was my first option, but couldn't find a way, maybe I'm missing something. Easier alternative, just ignore SSL, unsafe, but avoids all the headache.

**Do you have any alternatives?**
Can you pick up the certificates I supply to ca or cafile in my .npmrc file? That would be very helpful; otherwise, I end up having to subvert security just to install things.

### PR DESCRIPTION
**Pull request by cnishina**
closes #207

### CODE REVIEW

**Comment by cnishina** [comment]
@sjelin Could you look at my PR? I forgot to pass down some optional parameters.

File: lib/binaries/binary.ts [hunk 1]
```diff
@@ -81,14 +81,20 @@ export abstract class Binary {
...
    * Gets the url to download the file set by the version. This will use the XML if available.
    * If not, it will download from an existing url.
+   *
+   * @param {string} version The version we are looking for. This could also be 'latest'.
+   * @param {opt_proxy} string Option to get proxy URL.
+   * @param {opt_ignoreSSL} boolean Option to ignore SSL.
    */
-  getUrl(version?: string): Promise<BinaryUrl> {
+  getUrl(version?: string, opt_proxy?: string, opt_ignoreSSL?: boolean): Promise<BinaryUrl> {
+    this.opt_proxy = opt_proxy || this.opt_proxy;
```
Comment (sjelin) [inline lib/binaries/binary.ts]: As this currently stands, passing `opt_proxy` once will change the default value for all future calls.  Is that the desired behavior?

File: lib/binaries/binary.ts [hunk 2]
```diff
@@ -81,14 +81,20 @@ export abstract class Binary {
...
+    this.opt_ignoreSSL = opt_ignoreSSL || this.opt_ignoreSSL;
```
Comment (sjelin) [inline lib/binaries/binary.ts]: `y = x || y` style defaults do not work for booleans.  If `this.opt_ignoreSSL` is truthy then `opt_ignoreSSL || this.opt_ignoreSSL` will always be truthy, even if `opt_ignoreSSL` is explicitly `false`.  Instead, use `opt_ignoreSSL == undefined ? this.opt_ignoreSSL : opt_ignoreSSL`.

File: lib/binaries/binary.ts [hunk 3]
```diff
@@ -81,14 +81,20 @@ export abstract class Binary {
...
     if (this.alternativeDownloadUrl != null) {
       return Promise.resolve({url: '', version: ''});
     } else {
       return this.getVersionList().then(() => {
         version = version || Config.binaryVersions()[this.id()];
-        return this.configSource.getUrl(version).then(binaryUrl => {
+        return this.configSource.getUrl(version, opt_proxy, opt_ignoreSSL).then(binaryUrl => {
```
Comment (sjelin) [inline lib/binaries/binary.ts]: Should this be `opt_proxy` and `opt_ignoreSSL` or `this.opt_proxy` and `this.opt_ignoreSSL`?

Comment (sjelin) [inline lib/binaries/binary.ts]: If you don't want to use `this.opt_proxy` and `this.opt_ignoreSSL` here then it appears you're not using them anywhere (I even checked the child classes).

File: lib/binaries/config_source.ts [hunk 4]
```diff
@@ -14,7 +14,8 @@ export abstract class ConfigSource {
   opt_ignoreSSL: boolean;
   opt_proxy: string;
 
-  abstract getUrl(version: string): Promise<{url: string, version: string}>;
+  abstract getUrl(version: string, opt_proxy?: string, opt_ignoreSSL?: boolean):
```
Comment (sjelin) [inline lib/binaries/config_source.ts]: You're not actually using `opt_proxy` or `opt_ignoreSSL` here.  You want to remove the declarations above and do 

```ts
getUrl(version: string, public opt_proxy?: string, public opt_ignoreSSL?: boolean):
```

File: lib/binaries/chrome_xml.ts [hunk 5]
```diff
@@ -10,7 +10,9 @@ export class ChromeXml extends XmlConfigSource {
     super('chrome', Config.cdnUrls()['chrome']);
   }
 
-  getUrl(version: string): Promise<BinaryUrl> {
+  getUrl(version: string, opt_proxy?: string, opt_ignoreSSL?: boolean): Promise<BinaryUrl> {
+    this.opt_proxy = opt_proxy || this.opt_proxy;
+    this.opt_ignoreSSL = opt_ignoreSSL || this.opt_ignoreSSL;
```
Comment (sjelin) [inline lib/binaries/chrome_xml.ts]: Same comments as in `binary.ts`

File: lib/binaries/gecko_driver_github.ts [hunk 6]
```diff
@@ -10,7 +10,9 @@ export class GeckoDriverGithub extends GithubApiConfigSource {
     super('gecko', 'https://api.github.com/repos/mozilla/geckodriver/releases');
   }
 
-  getUrl(version: string): Promise<BinaryUrl> {
+  getUrl(version: string, opt_proxy?: string, opt_ignoreSSL?: boolean): Promise<BinaryUrl> {
+    this.opt_proxy = opt_proxy || this.opt_proxy;
+    this.opt_ignoreSSL = opt_ignoreSSL || this.opt_ignoreSSL;
```
Comment (sjelin) [inline lib/binaries/gecko_driver_github.ts]: Same comments as in `binary.ts`

File: lib/binaries/iedriver_xml.ts [hunk 7]
```diff
@@ -10,7 +10,9 @@ export class IEDriverXml extends XmlConfigSource {
     super('iedriver', Config.cdnUrls()['ie']);
   }
 
-  getUrl(version: string): Promise<BinaryUrl> {
+  getUrl(version: string, opt_proxy?: string, opt_ignoreSSL?: boolean): Promise<BinaryUrl> {
+    this.opt_proxy = opt_proxy || this.opt_proxy;
+    this.opt_ignoreSSL = opt_ignoreSSL || this.opt_ignoreSSL;
```
Comment (sjelin) [inline lib/binaries/iedriver_xml.ts]: Same comments as in `binary.ts`

File: lib/binaries/standalone_xml.ts [hunk 8]
```diff
@@ -10,7 +10,9 @@ export class StandaloneXml extends XmlConfigSource {
     super('standalone', Config.cdnUrls()['selenium']);
   }
 
-  getUrl(version: string): Promise<BinaryUrl> {
+  getUrl(version: string, opt_proxy?: string, opt_ignoreSSL?: boolean): Promise<BinaryUrl> {
+    this.opt_proxy = opt_proxy || this.opt_proxy;
+    this.opt_ignoreSSL = opt_ignoreSSL || this.opt_ignoreSSL;
```
Comment (sjelin) [inline lib/binaries/standalone_xml.ts]: Same comments as in `binary.ts`

File: lib/binaries/binary.ts (hunk 1 above)
Comment (cnishina) [inline lib/binaries/binary.ts]: I'm not concerned about this.

File: lib/binaries/binary.ts (hunk 2 above)
Comment (cnishina) [inline lib/binaries/binary.ts]: Yup, good catch.

File: lib/binaries/binary.ts (hunk 3 above)
Comment (royling) [inline lib/binaries/binary.ts]: They are used here https://github.com/angular/webdriver-manager/blob/83b7be0722c420e3440e66ba97b57b8d7311ea28/lib/binaries/config_source.ts#L41 for `XmlConfigSource` and https://github.com/angular/webdriver-manager/blob/83b7be0722c420e3440e66ba97b57b8d7311ea28/lib/binaries/config_source.ts#L141,L142 for `GithubApiConfigSource`.

But I am thinking if we could add these options in `config.json` for each CDN url, so that different config sources can have different options respectively.

Comment (cnishina) [inline lib/binaries/binary.ts]: I'll go through this and make sure they do the same thing. Thanks for pointing that out.

File: lib/binaries/config_source.ts (hunk 4 above)
Comment (cnishina) [inline lib/binaries/config_source.ts]: This is being used by all child classes of `ConfigSource`.

File: lib/binaries/chrome_xml.ts (hunk 5 above)
Comment (cnishina) [inline lib/binaries/chrome_xml.ts]: Done.

File: lib/binaries/iedriver_xml.ts (hunk 7 above)
Comment (cnishina) [inline lib/binaries/iedriver_xml.ts]: Done.

File: lib/binaries/standalone_xml.ts (hunk 8 above)
Comment (cnishina) [inline lib/binaries/standalone_xml.ts]: Done.

File: lib/binaries/config_source.ts (hunk 4 above)
Comment (sjelin) [inline lib/binaries/config_source.ts]: mmm, it appears I misread this section
