### PR TITLE
fix(chrome_driver): use the x64 binary if chrome driver version is greater than 2.23

### LINKED ISSUE #93: Unable to download chromedriver 2.24
When attempting to update, I get the following output:

```sh
./node_modules/.bin/webdriver-manager update --versions.chrome=2.24                                      
[08:31:32] I/file_manager - creating folder /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium
[08:31:32] I/downloader - selenium standalone: downloading version 2.53.1
[08:31:32] I/downloader - curl -o /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[08:31:32] I/downloader - chromedriver: downloading version 2.24
[08:31:32] I/downloader - curl -o /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[08:31:33] E/downloader - Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[08:31:33] E/downloader - Error: Got error Error: ENOENT: no such file or directory, stat '/path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip' from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
```

I am not certain, but this might be due to the fact that `mac32` is missing from [the download page](http://chromedriver.storage.googleapis.com/index.html?path=2.24/). I guess it has been replaced with mac64?

edit: it looks like this is also the case for [2.23](http://chromedriver.storage.googleapis.com/index.html?path=2.23/)

### PR DESCRIPTION
**Pull request by paradox41**
Closes #93

### CODE REVIEW

**Comment by paradox41** [comment]
@cnishina I've reopened this using my personal account so we can get this merged. CLA is signed already.

File: lib/binaries/chrome_driver.ts [hunk 1]
```diff
@@ -30,7 +30,13 @@ export class ChromeDriver extends Binary {
 
   suffix(ostype: string, arch: string): string {
     if (ostype === 'Darwin') {
-      return 'mac32' + this.suffixDefault;
+      // after chromedriver version 2.23, the name of the binary changed
+      // They no longer provide a 32 bit binary
+      if (parseFloat(this.version()) >= 2.23) {
```
Comment (darabos) [inline lib/binaries/chrome_driver.ts]: Please don't do this with floats. Float inaccuracies will likely affect `parseFloat` the same way as the literals. (But why take the risk?) But still `2.3` will compare greater than `2.23`, while `2.100` will compare as less.

Comment (paradox41) [inline lib/binaries/chrome_driver.ts]: Do you have any suggestions? `this.version()` is a string.

Comment (paradox41) [inline lib/binaries/chrome_driver.ts]: One suggestion I got from a colleague (@tomneyland) where we split on the `.` and check the major and minor version as ints. Maybe not the most elegant thing, but it seems pragmatic. Do you agree?

Comment (darabos) [inline lib/binaries/chrome_driver.ts]: > Do you have any suggestions? `this.version()` is a string.

You got me, I have no idea how to do this :). If you did it simply with strings, you would avoid the float inaccuracies, but that is the smaller part of the problem. You could use [`semver`](https://www.npmjs.com/package/semver) but who wants to add a dependency just for this. (Seems like it is part of NPM so it would not be an extra download, but still.)

If there are 64-bit binaries for earlier releases, you could just use `mac64` unconditionally.

> One suggestion I got from a colleague (@tomneyland) where we split on the . and check the major and minor version as ints. Maybe not the most elegant thing, but it seems pragmatic. Do you agree?

Should work well too!

(Don't take me too seriously, I am not part of the project, just happened to spot this. Whatever is fine by me.)

Comment (cnishina) [inline lib/binaries/chrome_driver.ts]: Adding `semver` is fine.

**Comment by paradox41** [comment]
@cnishina @darabos 

I think semver was a good idea, but unfortunately [semver doesn't like invalid / incomplete versions](https://github.com/npm/node-semver/issues/168) (like what Chromedriver uses).

```js
> var semver = require('semver')
undefined
> semver.valid('2.23')
null
> semver.valid('2.23.0')
'2.23.0'
```

So I had to "make it" valid by adding a patch version at the end. Not ideal as we can't guarantee Chromedriver won't ever add a patch version, but it is cleaner than comparing floats.

Please let me know what you think.

**Comment by paradox41** [comment]
@cnishina another option is to just do `this.version().split('.')`, but even this might break (unless we write it very defensively) if a patch version is added.

Thoughts?

**Comment by paradox41** [comment]
friendly ping @cnishina for re-review

**Comment by TomNeyland** [comment]
@paradox41 @cnishina any updates on this?

**Comment by paradox41** [comment]
@cnishina any thoughts on the updates and my comments?

**Comment by cnishina** [comment]
Sorry for the delay. Assigning to Michael to follow up on this.

**Comment by mgiambalvo** [comment]
I'd say go ahead with using semver, but please add a check that the version only contains a major and minor before appending the ".0". Something simple like checking `this.version().split('.').length == 2` would be fine.

**Comment by paradox41** [comment]
@mgiambalvo changes made.

**Comment by mgiambalvo** [comment]
Thanks!

**Comment by paradox41** [comment]
Thank you!

**Comment by holm** [comment]
It would be great to get this released, since Chrome 54 is now out, which requires chromedriver 2.24. And without a new webdriver-manager release, we can't upgrade chromedriver beyond 2.22. 

Thanks!
