### PR TITLE
fix(ie): Use 32-bit version by default for IEDriver

### LINKED ISSUE #180: Use 32-bit version by default for IEDriver
By default, always use the 32-bit version over x64. For users that want to try the x64 version, we should add a flag.

See discussion: https://github.com/angular/protractor/issues/1506 and https://github.com/angular/protractor/issues/1999

### PR DESCRIPTION
**Pull request by cnishina**
closes #180

### CODE REVIEW

File: lib/cmds/start.ts [hunk 1]
```diff
@@ -153,7 +154,7 @@ function start(options: Options) {
         path.resolve(outputDir, binaries[GeckoDriver.id].executableFilename(osType)));
   }
   if (downloadedBinaries[IEDriver.id] != null) {
-    if (options[Opt.IE32].getBoolean()) {
+    if (options[Opt.IE32].getBoolean() || options[Opt.IE].getBoolean()) {
```
Comment (sjelin) [inline lib/cmds/start.ts]: Or `IE64`?

File: lib/cmds/update.ts [hunk 2]
```diff
@@ -150,13 +154,13 @@ function update(options: Options): Promise<void> {
...
   }
-  if (ie) {
+  if (ie64) {
     let binary = binaries[IEDriver.id];
     binary.arch = Config.osArch();  // Win32 or x64
     updateBrowserFile(binary, outputDir);
     promises.push(updateBinary(binary, outputDir, proxy, ignoreSSL));
   }
-  if (ie32) {
+  if (ie || ie32) {
```
Comment (sjelin) [inline lib/cmds/update.ts]: `if ((ie && !ie64) || ie32)`?

File: lib/files/file_manager.ts [hunk 3]
```diff
@@ -122,7 +122,9 @@ export class FileManager {
         }
         // if the suffix does not match the executable,
         // the binary is something like: .exe and .zip
-        else if (existFile.indexOf(binary.suffix(osType, arch)) === -1) {
+        else if (
```
Comment (sjelin) [inline lib/files/file_manager.ts]: Why is this change here?

File: spec/cmds/status_spec.ts [hunk 4]
```diff
@@ -18,8 +18,6 @@ describe('status', () => {
   // geckodriver {{config version}} [last] [default]
   // standalone 2.24 [last], {{config version}} [default]
   beforeAll((done) => {
-    Config.osType_ = 'Linux';
-    Config.osArch_ = 'x64';
```
Comment (sjelin) [inline spec/cmds/status_spec.ts]: Why this change?

File: lib/cmds/opts.ts [hunk 5]
```diff
@@ -58,8 +59,11 @@ opts[STANDALONE] = new Option(
 opts[CHROME] =
     new Option(CHROME, 'Install or update chromedriver', 'boolean', ChromeDriver.isDefault);
 opts[GECKO] = new Option(GECKO, 'Install or update geckodriver', 'boolean', GeckoDriver.isDefault);
-opts[IE] = new Option(IE, 'Install or update ie driver', 'boolean', IEDriver.isDefault);
+opts[IE] = new Option(
+    IE, 'Install or update ie driver (defaults downloading 32-bit version)', 'boolean',
+    IEDriver.isDefault);
 opts[IE32] = new Option(IE32, 'Install or update 32-bit ie driver', 'boolean', IEDriver.isDefault);
+opts[IE64] = new Option(IE64, 'Install or update x64 iedriver', 'boolean', IEDriver.isDefault);
```
Comment (sjelin) [inline lib/cmds/opts.ts]: Shouldn't the default be `IEDriver.is64Default`?

Comment (cnishina) [inline lib/cmds/opts.ts]: `isDefault` is a boolean to either to download or not download. The arch version is decided elsewhere.

File: lib/cmds/start.ts (hunk 1 above)
Comment (cnishina) [inline lib/cmds/start.ts]: This conditional sets the architecture to 32-bit. By default it is the system's arch which is probably x64.

File: lib/cmds/update.ts (hunk 2 above)
Comment (cnishina) [inline lib/cmds/update.ts]: ie, ie32, and ie64 are set from different flag options.

An example: a user downloads the 32bit version:
```
webdriver-manager update --ie

ie = true
ie32 = false
ie64 = false

webdriver-manager update --ie32

ie = false
ie32 = true
ie64 = false
```

An odd case: the user wants to download the 32bit version and 64bit version. We will let them download both. However, starting the server, the user would then have to specify if they want to use the 32-bit version if not it would default to the system arch.
```
webdriver-manager update --ie32 --ie64

ie = false
ie32 = true
ie64 = true
```

File: lib/files/file_manager.ts (hunk 3 above)
Comment (cnishina) [inline lib/files/file_manager.ts]: This is an extra check... current implementation of this needs some fixing. This is because downloading a file before 2.23 suffix is mac32.zip and this method is returning mac64.zip. Unfortunately, when we get the suffix the version is not set.

Not having extra checks:
```
webdriver-manager status

chromedriver versions available: 2.20 [last], 2.20mac32.zip, 2.26 [default]
```

Adding a TODO(cnishina) to fix this.

File: spec/cmds/status_spec.ts (hunk 4 above)
Comment (cnishina) [inline spec/cmds/status_spec.ts]: It does not matter which os arch and type we are downloading.

File: lib/cmds/opts.ts [hunk 6]
```diff
@@ -58,8 +59,12 @@ opts[STANDALONE] = new Option(
 opts[CHROME] =
     new Option(CHROME, 'Install or update chromedriver', 'boolean', ChromeDriver.isDefault);
 opts[GECKO] = new Option(GECKO, 'Install or update geckodriver', 'boolean', GeckoDriver.isDefault);
-opts[IE] = new Option(IE, 'Install or update ie driver', 'boolean', IEDriver.isDefault);
-opts[IE32] = new Option(IE32, 'Install or update 32-bit ie driver', 'boolean', IEDriver.isDefault);
+opts[IE] = new Option(
+    IE, 'Install or update ie driver (defaults downloading 32-bit version)', 'boolean',
```
Comment (sjelin) [inline lib/cmds/opts.ts]: Not a default - always 32 bit.

File: lib/cmds/update.ts [hunk 7]
```diff
@@ -74,12 +74,16 @@ function update(options: Options): Promise<void> {
   let gecko = options[Opt.GECKO].getBoolean();
   let ie: boolean = false;
   let ie32: boolean = false;
```
Comment (sjelin) [inline lib/cmds/update.ts]: Why two variables if they're just gonna be the same thing anyway?  Combine both into `ie32`

File: lib/cmds/start.ts [hunk 8]
```diff
@@ -46,6 +46,7 @@ if (Config.osType() === 'Windows_NT') {
   prog.addOption(Opts[Opt.VERSIONS_IE])
       .addOption(Opts[Opt.IE32])
       .addOption(Opts[Opt.IE])
+      .addOption(Opts[Opt.IE64])
```
Comment (sjelin) [inline lib/cmds/start.ts]: As per our discussion offline, remove the `IE` and `IE32` flags and default `arch` to `Win32`

**Comment by cnishina** [comment]
@sjelin ping... for review.

File: lib/binaries/ie_driver.ts [hunk 9]
```diff
@@ -10,7 +10,8 @@ export class IEDriver extends Binary {
   static os = [OS.Windows_NT];
   static id = 'ie';
   static versionDefault = Config.binaryVersions().ie;
-  static isDefault = false;
+  static isDefault32 = false;
+  static isDefault64 = false;
   static shortName = ['ie', 'ie32'];
```
Comment (sjelin) [inline lib/binaries/ie_driver.ts]: Should the short names be `['ie', 'ie64']` now?

Comment (cnishina) [inline lib/binaries/ie_driver.ts]: Would you imagine that. `shortName` is not used at all. I must have had it there for something and abandoned it. Removing all `shortName`'s. :confused:

File: lib/binaries/binary.ts [hunk 10]
```diff
@@ -21,7 +21,6 @@ export interface BinaryMap<T extends Binary> { [id: string]: T; }
 export class Binary {
   static os: OS[];                // the operating systems, the binary can run on
   static id: string;              // the binaries key identifier
-  static isDefault: boolean;      // to download by default
   static versionDefault: string;  // a static default version variable
   static shortName: string[];     // the names used for a binary download
```
Comment (sjelin) [inline lib/binaries/binary.ts]: If `shortName` is gone remove it here too.  Please do a `grep` too do double check

Comment (cnishina) [inline lib/binaries/binary.ts]: Visual grep failed. Will fix.

Comment (cnishina) [inline lib/binaries/binary.ts]: Actually, it looks like I didn't commit that code... fixed now.
